#!/usr/bin/env python3
#
##############################################################################
#
# MODULE:       Sorgenti del Brembo di Carona (MAPCALC)
#
# AUTHOR(S):    E. Croce
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Thu Dec 14 12:24:33 2023
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main(options, flags):
    run_command("r.mapcalc",
                expression="Regression = 10.047157892 + ( DTM_SBC  * -0.003264071 ) + ( Slope * -0.202716735 )",
                region="current")

    run_command("r.mapcalc",
                expression="Probability_Surface = ( exp ( Regression ) ) / ( 1+ ( exp ( Regression ) ) )",
                region="current")

    run_command("r.mapcalc",
                expression="Prob01 = Probability_Surface >= 0.1",
                region="current")

    run_command("r.mapcalc",
                expression="Prob02 = Probability_Surface >= 0.2",
                region="current")

    run_command("r.mapcalc",
                expression="Prob03 = Probability_Surface >= 0.3",
                region="current")

    run_command("r.mapcalc",
                expression="Prob04 = Probability_Surface >= 0.4",
                region="current")

    run_command("r.mapcalc",
                expression="Prob05 = Probability_Surface >= 0.5",
                region="current")

    run_command("r.mapcalc",
                expression="Prob06 = Probability_Surface >= 0.6",
                region="current")

    run_command("r.mapcalc",
                expression="Prob07 = Probability_Surface >= 0.7",
                region="current")

    run_command("r.mapcalc",
                expression="Prob08 = Probability_Surface >= 0.8",
                region="current")

    run_command("r.mapcalc",
                expression="Prob09 = Probability_Surface >= 0.9",
                region="current")

    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main(options, flags))
